# Generated by Django 4.0.4 on 2022-04-21 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('bio', models.TextField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('main_category', models.CharField(choices=[('Mens', 'Mens'), ('Accessories', 'Accessories'), ('Womens', 'Womens')], max_length=30)),
                ('category', models.CharField(choices=[('Bottoms', 'Bottoms'), ('Tank Tops', 'Tank Tops'), ('Shorts', 'Shorts'), ('Crop Tops', 'Crop Tops'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Equipments', 'Equipments'), ('Headwears', 'Headwears'), ('Joggers', 'Joggers'), ('Leggings', 'Leggings'), ('Sports Bras', 'Sports Bras'), ('Gym Bags', 'Gym Bags'), ('Hoddies & Jackets', 'Hoddies & Jackets')], max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('coditions', models.CharField(choices=[('Used - Like New', 'Used - Like New'), ('Used - Fair', 'Used - Fair'), ('New', 'New'), ('Used - Good', 'Used - Good')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
