# Generated by Django 4.0.4 on 2022-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coditions',
        ),
        migrations.AddField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('New', 'New'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair'), ('Used - Like New', 'Used - Like New')], default=0.5, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bottoms', 'Bottoms'), ('Leggings', 'Leggings'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Equipments', 'Equipments'), ('Headwears', 'Headwears'), ('Crop Tops', 'Crop Tops'), ('Gym Bags', 'Gym Bags'), ('Shorts', 'Shorts'), ('Tank Tops', 'Tank Tops'), ('Joggers', 'Joggers'), ('Sports Bras', 'Sports Bras')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Mens', 'Mens'), ('Womens', 'Womens')], max_length=30),
        ),
    ]
