# Generated by Django 4.0.4 on 2022-04-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_product_coditions_product_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bottoms', 'Bottoms'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Joggers', 'Joggers'), ('Crop Tops', 'Crop Tops'), ('Tank Tops', 'Tank Tops'), ('Equipments', 'Equipments'), ('Gym Bags', 'Gym Bags'), ('Headwears', 'Headwears'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Shorts', 'Shorts'), ('Leggings', 'Leggings'), ('Sports Bras', 'Sports Bras')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Fair', 'Used - Fair'), ('New', 'New'), ('Used - Good', 'Used - Good'), ('Used - Like New', 'Used - Like New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Womens', 'Womens'), ('Mens', 'Mens')], max_length=30),
        ),
    ]
