# Generated by Django 4.0.4 on 2022-04-27 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_quantity_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Leggings', 'Leggings'), ('Bottoms', 'Bottoms'), ('Tank Tops', 'Tank Tops'), ('Sports Bras', 'Sports Bras'), ('Shorts', 'Shorts'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Headwears', 'Headwears'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Equipments', 'Equipments'), ('Crop Tops', 'Crop Tops'), ('Gym Bags', 'Gym Bags'), ('Joggers', 'Joggers')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Good', 'Used - Good'), ('Used - Like New', 'Used - Like New'), ('New', 'New'), ('Used - Fair', 'Used - Fair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Womens', 'Womens'), ('Accessories', 'Accessories'), ('Mens', 'Mens')], max_length=30),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(to='main_app.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
