# Generated by Django 4.0.4 on 2022-04-27 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_category_alter_product_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('product', models.ManyToManyField(to='main_app.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Joggers', 'Joggers'), ('Gym Bags', 'Gym Bags'), ('Bottoms', 'Bottoms'), ('Shorts', 'Shorts'), ('Leggings', 'Leggings'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Crop Tops', 'Crop Tops'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Sports Bras', 'Sports Bras'), ('Headwears', 'Headwears'), ('Tank Tops', 'Tank Tops'), ('Equipments', 'Equipments')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair'), ('Used - Like New', 'Used - Like New'), ('New', 'New')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
