# Generated by Django 4.0.4 on 2022-04-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_orders_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-shirts & Tops', 'T-shirt & Tops'), ('Bottoms', 'Bottoms'), ('Joggers', 'Joggers'), ('Shorts', 'Shorts'), ('Leggings', 'Leggings'), ('Headwears', 'Headwears'), ('Equipments', 'Equipments'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Sports Bras', 'Sports Bras'), ('Tank Tops', 'Tank Tops'), ('Gym Bags', 'Gym Bags'), ('Crop Tops', 'Crop Tops')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('New', 'New'), ('Used - Fair', 'Used - Fair'), ('Used - Good', 'Used - Good'), ('Used - Like New', 'Used - Like New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Womens', 'Womens'), ('Mens', 'Mens'), ('Accessories', 'Accessories')], max_length=30),
        ),
    ]
