# Generated by Django 4.0.4 on 2022-04-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_product_quantity_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-shirts & Tops', 'T-shirt & Tops'), ('Headwears', 'Headwears'), ('Leggings', 'Leggings'), ('Bottoms', 'Bottoms'), ('Shorts', 'Shorts'), ('Sports Bras', 'Sports Bras'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Tank Tops', 'Tank Tops'), ('Equipments', 'Equipments'), ('Gym Bags', 'Gym Bags'), ('Joggers', 'Joggers'), ('Crop Tops', 'Crop Tops')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('New', 'New'), ('Used - Good', 'Used - Good'), ('Used - Like New', 'Used - Like New'), ('Used - Fair', 'Used - Fair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Womens', 'Womens'), ('Accessories', 'Accessories'), ('Mens', 'Mens')], max_length=30),
        ),
    ]
