# Generated by Django 4.0.4 on 2022-04-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_product_category_alter_product_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Crop Tops', 'Crop Tops'), ('Shorts', 'Shorts'), ('Joggers', 'Joggers'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Equipments', 'Equipments'), ('Gym Bags', 'Gym Bags'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Tank Tops', 'Tank Tops'), ('Headwears', 'Headwears'), ('Sports Bras', 'Sports Bras'), ('Leggings', 'Leggings'), ('Bottoms', 'Bottoms')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Mens', 'Mens'), ('Womens', 'Womens')], max_length=30),
        ),
    ]
