# Generated by Django 4.0.4 on 2022-04-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Crop Tops', 'Crop Tops'), ('Shorts', 'Shorts'), ('Joggers', 'Joggers'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Leggings', 'Leggings'), ('Gym Bags', 'Gym Bags'), ('Sports Bras', 'Sports Bras'), ('Tank Tops', 'Tank Tops'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Equipments', 'Equipments'), ('Bottoms', 'Bottoms'), ('Headwears', 'Headwears')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Fair', 'Used - Fair'), ('New', 'New'), ('Used - Good', 'Used - Good'), ('Used - Like New', 'Used - Like New')], max_length=20),
        ),
    ]
