# Generated by Django 4.0.4 on 2022-04-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_product_slug_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Leggings', 'Leggings'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Bottoms', 'Bottoms'), ('Crop Tops', 'Crop Tops'), ('Joggers', 'Joggers'), ('Shorts', 'Shorts'), ('Sports Bras', 'Sports Bras'), ('Tank Tops', 'Tank Tops'), ('Gym Bags', 'Gym Bags'), ('Headwears', 'Headwears'), ('Equipments', 'Equipments'), ('T-shirts & Tops', 'T-shirt & Tops')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Like New', 'Used - Like New'), ('Used - Fair', 'Used - Fair'), ('Used - Good', 'Used - Good'), ('New', 'New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Accessories', 'Accessories'), ('Womens', 'Womens')], max_length=30),
        ),
    ]
