# Generated by Django 4.0.4 on 2022-04-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_orderitem_ordered_orderitem_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Crop Tops', 'Crop Tops'), ('Gym Bags', 'Gym Bags'), ('Bottoms', 'Bottoms'), ('Leggings', 'Leggings'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Joggers', 'Joggers'), ('Shorts', 'Shorts'), ('Sports Bras', 'Sports Bras'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Headwears', 'Headwears'), ('Equipments', 'Equipments'), ('Tank Tops', 'Tank Tops')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('New', 'New'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair'), ('Used - Like New', 'Used - Like New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Womens', 'Womens'), ('Accessories', 'Accessories'), ('Mens', 'Mens')], max_length=30),
        ),
    ]
