# Generated by Django 4.0.4 on 2022-04-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_product_category_alter_product_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sports Bras', 'Sports Bras'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Equipments', 'Equipments'), ('Joggers', 'Joggers'), ('Headwears', 'Headwears'), ('Crop Tops', 'Crop Tops'), ('Shorts', 'Shorts'), ('Leggings', 'Leggings'), ('Bottoms', 'Bottoms'), ('Tank Tops', 'Tank Tops'), ('Gym Bags', 'Gym Bags'), ('T-shirts & Tops', 'T-shirt & Tops')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair'), ('Used - Like New', 'Used - Like New'), ('New', 'New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Accessories', 'Accessories'), ('Womens', 'Womens')], max_length=30),
        ),
    ]
