# Generated by Django 4.0.4 on 2022-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_product_category_alter_product_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Joggers', 'Joggers'), ('Equipments', 'Equipments'), ('Headwears', 'Headwears'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Sports Bras', 'Sports Bras'), ('Gym Bags', 'Gym Bags'), ('Shorts', 'Shorts'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Bottoms', 'Bottoms'), ('Tank Tops', 'Tank Tops'), ('Crop Tops', 'Crop Tops'), ('Leggings', 'Leggings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('New', 'New'), ('Used - Like New', 'Used - Like New'), ('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Womens', 'Womens'), ('Mens', 'Mens')], max_length=30),
        ),
    ]
