# Generated by Django 4.0.4 on 2022-04-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_product_category_alter_product_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gym Bags', 'Gym Bags'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Sports Bras', 'Sports Bras'), ('Bottoms', 'Bottoms'), ('Crop Tops', 'Crop Tops'), ('Shorts', 'Shorts'), ('Tank Tops', 'Tank Tops'), ('Equipments', 'Equipments'), ('Headwears', 'Headwears'), ('Joggers', 'Joggers'), ('Leggings', 'Leggings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Good', 'Used - Good'), ('New', 'New'), ('Used - Like New', 'Used - Like New'), ('Used - Fair', 'Used - Fair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Womens', 'Womens'), ('Accessories', 'Accessories'), ('Mens', 'Mens')], max_length=30),
        ),
    ]
