# Generated by Django 4.0.4 on 2022-04-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_product_category_alter_product_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hoddies & Jackets', 'Hoddies & Jackets'), ('Gym Bags', 'Gym Bags'), ('Sports Bras', 'Sports Bras'), ('Joggers', 'Joggers'), ('Leggings', 'Leggings'), ('Shorts', 'Shorts'), ('Equipments', 'Equipments'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Headwears', 'Headwears'), ('Crop Tops', 'Crop Tops'), ('Bottoms', 'Bottoms'), ('Tank Tops', 'Tank Tops')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Good', 'Used - Good'), ('Used - Fair', 'Used - Fair'), ('New', 'New'), ('Used - Like New', 'Used - Like New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Womens', 'Womens'), ('Mens', 'Mens'), ('Accessories', 'Accessories')], max_length=30),
        ),
    ]
