# Generated by Django 4.0.4 on 2022-04-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_product_category_alter_product_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tank Tops', 'Tank Tops'), ('Shorts', 'Shorts'), ('Crop Tops', 'Crop Tops'), ('Leggings', 'Leggings'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Gym Bags', 'Gym Bags'), ('Sports Bras', 'Sports Bras'), ('Joggers', 'Joggers'), ('Bottoms', 'Bottoms'), ('Equipments', 'Equipments'), ('Headwears', 'Headwears'), ('Hoddies & Jackets', 'Hoddies & Jackets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Womens', 'Womens'), ('Mens', 'Mens'), ('Accessories', 'Accessories')], max_length=30),
        ),
    ]
