# Generated by Django 4.0.4 on 2022-04-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_product_category_alter_product_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Sports Bras', 'Sports Bras'), ('Joggers', 'Joggers'), ('Bottoms', 'Bottoms'), ('Leggings', 'Leggings'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Headwears', 'Headwears'), ('Equipments', 'Equipments'), ('Shorts', 'Shorts'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Gym Bags', 'Gym Bags'), ('Tank Tops', 'Tank Tops'), ('Crop Tops', 'Crop Tops')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Good', 'Used - Good'), ('New', 'New'), ('Used - Fair', 'Used - Fair'), ('Used - Like New', 'Used - Like New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Womens', 'Womens'), ('Mens', 'Mens')], max_length=30),
        ),
    ]
