# Generated by Django 4.0.4 on 2022-04-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_product_category_alter_product_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Headwears', 'Headwears'), ('Tank Tops', 'Tank Tops'), ('Joggers', 'Joggers'), ('Crop Tops', 'Crop Tops'), ('Hoddies & Jackets', 'Hoddies & Jackets'), ('Shorts', 'Shorts'), ('Sports Bras', 'Sports Bras'), ('Leggings', 'Leggings'), ('T-shirts & Tops', 'T-shirt & Tops'), ('Bottoms', 'Bottoms'), ('Gym Bags', 'Gym Bags'), ('Equipments', 'Equipments')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='conditions',
            field=models.CharField(choices=[('Used - Good', 'Used - Good'), ('Used - Like New', 'Used - Like New'), ('Used - Fair', 'Used - Fair'), ('New', 'New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Womens', 'Womens'), ('Accessories', 'Accessories')], max_length=30),
        ),
    ]
